name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the docker-compose redis cluster stack
        run: docker-compose -f docker-compose.yml up -d

    - name: Check running containers
      run: docker ps -a

    - name: Check logs
      run: docker logs redis-cluster-init

    - name: docker exec node-client node index.js

    