name: Docker Image CI

on:
  push: 
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Add secret redis root ca cert into layers folder
      env:
        REDIS_PROD_CA_CRT: ${{ secrets.REDIS_PROD_CA_CRT }}
      run: |
        echo "$REDIS_PROD_CA_CRT" | base64 --decode > ${HOME}/layer/certs/rootCA.crt

    - name: Build the redis instances
      run: docker-compose -f redis-instance.yml up -d

    - name: Check running containers
      run: docker ps -a

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    
    - name: Install Dependencies
      run: npm install --quiet

    - name: Run node client
      run: node index.js

    