name: Running Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    # container: node:12.20.0-alpine3.10

    services:
      redis:
        # Docker Hub image
        image: redis:6.0.5
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install Default JDK
        run: sudo apt-get install default-jdk

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Installing Dependencies
        run: npm ci

      - name: Connect to Redis
        run: node index.js
        env:
          # The hostname used to communicate with the Redis service container
          REDIS_HOST: redis
          # The default Redis port
          REDIS_PORT: 6379

      - name: Run Tests
        run: npm run test
        env:
          # The hostname used to communicate with the Redis service container
          REDIS_HOST: redis
          # The default Redis port
          REDIS_PORT: 6379