name: Running Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    container: node:12.20.0-alpine3.10
  
    steps:
      - uses: actions/checkout@v2

      - name: Pull Redis Docker container
        run: run: docker-compose -f redis-instance.yml up -d

      - name: Installing Dependencies
        run: npm ci

      - name: Running Tests
        run: node index.js
