name: Running Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Pull Redis Docker container
        run: docker-compose -f redis-instance.yml up -d
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Installing Dependencies
        run: npm ci

      - name: Running Tests
        run: node index.js
