name: Running Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    # container: node:12.20.0-alpine3.10

    services:
      redis:
        # Docker Hub image
        image: redis:6.0.5
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Docker build for rocket
        run: docker build -f Dockerfile 

      - name: Run test suite
        run: docker exec npm run test

      # - name: Installing Dependencies
      #   run: npm ci

      # - name: Connect to Redis
      #   run: node index.js
      #   env:
      #     # The hostname used to communicate with the Redis service container
      #     REDIS_HOST: redis
      #     # The default Redis port
      #     REDIS_PORT: 6379

      # - name: Run Tests
      #   run: npm run test
      #   env:
      #     # The hostname used to communicate with the Redis service container
      #     REDIS_HOST: redis
      #     # The default Redis port
      #     REDIS_PORT: 6379
branding:
  icon: 'check-circle'
  color: 'green'