name: Running Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    container: node:12.20.0-alpine3.10

    services:
      redis:
        # Docker Hub image
        image: bitnami/redis-cluster:latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing Dependencies
        run: npm ci

      - name: Running Tests
        run: node index.js
